### ISSUE TITLE
CHECKLIST

### ISSUE THREAD

**Issue by lubrand** [hedra-editora/sofocles_ediporei#1]
Checklists
---------

### Regras gerais (lembrar antes de começar)

* PASTA LOCAL: ~\LATEX\<autor_titulo> ( = github)
* ...

-----------------------------------------------

### Abertura de projeto

* Criar board no Odoo 
* Definir data de fechamento e data de expiração (fim da pré-venda)
* Cadastros de autor no Odoo
* Arquivos iniciais em \PRODUCAO\ORIGINAIS

-----------------------------------------------

### Diagramação 
... @jorge

### Revisão
... @luiza

### Capa

* [x] Recalcular Lombada
* [x] Conferir Formato (altura, largura e tamanho da orelha)
* [x] Conferir Coleção
* [x] Título: ler pausadamente título da capa e do miolo
* [x] Autor: item
* [x] Trecho de capa: conferir com Miolo
* [x] Texto de orelha: leitura de duas pessoas
* [x] Imagem de capa (não esquecer de colocar crédito de imaem depois dentro do livro)
* [x] Nome do capista nos créditos
* [x] Isbn (Mandar imagem EPS): conferir com planilha no google drive em goo.gl/QYVTex
Se for bolso:
* [x] Rubricas de capa devem ter gênero: "Autor" "Autora"
* [x] Seguir modelo _Organização e tradução do grego_
* [x] Verificar se obra não faz parte de subcoleção
* [x] Verifcar no miolo se constam resumos do autor, da obra e das pessoas envolvidas. Se houver subcoleção, verificar se existe também texto sobre.

### Página de crédito (fichatecnica.sty)

Ex: \newcommand{\<COMANDO>}{<CONTEÚDO>} em fichatecnica.sty (na pasta do livros)

Lista de comandos:
* [ ] \titulo  				
* [ ] \subtit  				
* [ ] \autor  				
* [x] \ISBN
* [ ] \eISBN
* [x] \ano
* [x] \organizador  				
* [ ] \introdutor			
* [x] \tradutor  				
* [ ] \prefacio  				
* [ ] \apresentador  				
* [x] \edicao{Jorge Sallum}
* [x] \coedicao
* [x] \assistencia
* [x] \revisao
* [ ] \preparacao
* [x] \capa
* [x] \imagemcapa  				
* [x] \agradecimentos
* [ ] \indicacao
* [x] \copyrightlivro
* [x] \copyrighttraducao
* [x] \copyrightorganizacao
* [ ] \copyrightilustracao
* [ ] \copyrightintroducao
* [x] \titulooriginal
* [ ] \edicaoconsultada
* [ ] \primeiraedicao
* [ ] \grafica  				
* [ ] \papelmiolo  				
* [ ] \gramaturamiolo  				

### Fechamento

* [x] verificar se código ID no final do livro bate com a versão do github
* [x] arquivo de miolo está em \ARQUIVOSGERAIS?
* [x] arquivo de capa está em \ARQUIVOSGERAIS?
* [ ] arquivo de EPUB em \ARQUIVOSGERAIS\EPUB
* [x] arquivos estão em github?
* [x] checklist de página de crédito
* [ ] Criar MO de lançamento 

### Cadastros

 * Internos
	* Odoo (@jorgesallum)
	* Site (@anaclara)
 * Indexadores (metadados)
	* Mercado editorial (@anaclara)
	* Metabooks @(jorgesallum)
 * Integradores (distribuição, PoD, logística, pagamentos)
	* Meta (@jorgesallum)
	* Bookwire (@rodney)
 * Repositórios ("netflix")
	* Nuvem de livros (@jorgesallum)
	* Árvore de livros (@luiza)

### Marketing

 * @editorial
	* [ ] Arquivos OK
	* [ ] Release
    * [ ] Texto para _blog_
	* [ ] Booklet (x30)
	* [ ] Cadastros
	* [ ] Repositórios
	* [ ] Com o autor: Lançamentos marcado?
	* [ ] Com o autor: Lista vip do autor
	* [ ] Com o autor: Lista de jornalista
 
 * @marketing
	* [ ] _Newsletter_ para clientes
	* [ ] Texto para Facebook
	* [ ] Texto para Instagram
    * [ ] Tuites
  	* [ ] parceiros de divulgacao (blogueiros)
  	* [ ] kit para imprensa (envio)

 * @comercial
	* [ ] Apresentação para compradores (@ricardo)
	* [ ] Tiragem mínima para impressão
